general:
  interval: 10 # in seconds
logging:
  enabled: true
plex:
  servers: [] # list of servers to gather metrics for
  api_token:
  username:
  password:
influxdb:
  server_address:
  port:
  database:
  ssl:
  ignore_ssl_check:
datadog:
  app_token:
  api_token:
  prefix:
